Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,7 +1,9 @@
-name: Basic CI Pipeline
+name: Advanced CI Pipeline
 
 on:
   push:
+    branches: [ main ]
+  pull_request:
     branches: [ main ]
 
 jobs:
@@ -12,5 +14,21 @@ jobs:
     - name: Checkout code
       uses: actions/checkout@v3
 
-    - name: Project check
-      run: echo "Project uploaded successfully and pipeline is working!"
+    - name: List files
+      run: ls -R
+
+    - name: Check for important files
+      run: |
+        if [ ! -f README.md ]; then
+          echo "README.md missing "
+          exit 1
+        fi
+
+    - name: Install HTML validator
+      run: npm install -g htmlhint
+
+    - name: Run HTML check
+      run: htmlhint "**/*.html" || true
+
+    - name: Done
+      run: echo "Pipeline completed successfully "
